---spring:  profiles:    active:    - peer1
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: dev
server:
  port: 7999
eureka:  server:    enable-self-preservation: false
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer1:7999/eureka/
      ---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1
server:
  port: 8000
eureka:  server:    enable-self-preservation: false
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8001
eureka:  server:    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer3:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://peer1:8000/eureka/,http://peer2:8001/eureka/